# Site settings
title: weiyentan.github.io
description: 'A Journal about automation using different platforms'
url: 'http://weiyentan.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: weiyentan.github.io

author:
  name: 'Wei-Yen Tan'
  email: weiyen.tan@gmail.com
  twitter_username: weiyen
  facebook_username: weiyentan
  github_username:  weiyentan
  linkedin_username:  weiyentan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

#sass:
#    sass_dir: _sass
#    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
